#!/usr/bin/env node
// Set a repo up for Nightwatch, end to end, from a fresh session: preflight,
// a clone that never pushes, the trust entry the headless child needs, the
// check command, the state directory, the kill switch, and a dry run that
// proves the plumbing before a real night pays for it.
//
//   node init.mjs [--repo <path>] [--name <name>] [--clone-root <dir>]
//                 [--check-cmd "<line>"]... [--set-switch]
//                 [--no-dry-run] [--report] [--json]
//
// Every step is idempotent and reports one of `done`, `skipped (already …)`,
// `needs you: …` or `failed: …`; the run stops at the first `failed`, and at a
// `needs you` on the check (there is nothing to prove without one). `--report`
// changes nothing at all: it prints what each step would do, plus the check
// commands the repo's CI workflows suggest.
//
// What init never touches: the repo's branches, its remote, GitHub, and CI.
// It commits nothing and opens no pull request — the only push in the whole of
// Nightwatch is the morning one. A generated check lives in the state dir, not
// in the repo; commit a `scripts/check` yourself if you want it there.
//
// Exports `plan(opts)` → `Step[]` (a pure enumeration, no side effects) and
// `run(opts)` → `{ steps, ok }`. Every subprocess goes through `exec()`, as an
// argv array rather than a shell string.

import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
  chmodSync,
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  renameSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const RUN_SH = join(HERE, "run.sh");

// The launcher runs every acceptance command under `timeout`, which on macOS
// comes from coreutils; `caffeinate` keeps the night awake; `shasum` is how the
// launcher checks the generated check has not been swapped.
const REQUIRED_BINS = ["claude", "gh", "jq", "caffeinate", "node", "shasum", "timeout"];

// A CI step worth running locally. Deliberately a keyword list rather than a
// judgement: init suggests, the human (or the skill) chooses.
const CHECK_WORDS = /\b(fmt|clippy|test|nextest|lint|typos|machete|deny|xtask|check)\b/;

// ---------------------------------------------------------------- primitives

/** One subprocess, argv array, never a shell string. */
export function exec(cmd, args, opts = {}) {
  const res = spawnSync(cmd, args, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"], ...opts });
  return {
    code: res.status === null ? 1 : res.status,
    stdout: (res.stdout || "").trim(),
    stderr: (res.stderr || "").trim(),
    error: res.error,
  };
}

/** PATH lookup in Node, so a test can hide a binary the host really has. */
function onPath(name) {
  for (const dir of (process.env.PATH || "").split(":")) {
    if (!dir) continue;
    const p = join(dir, name);
    try {
      if (statSync(p).isFile()) return true;
    } catch {
      /* next */
    }
  }
  return false;
}

/**
 * The one rendering of CHECK every consumer sees — the launcher's own run, the
 * engine's args JSON, the linter, the Acceptance line. A byte-for-byte port of
 * `check_cmd` in run.sh: double quotes, because the engine wraps each command
 * in `bash -c '<command>'` and single quotes would not survive that.
 */
export function checkCmd(check) {
  if (/^[A-Za-z0-9_./-]+$/.test(check)) return check;
  if (/["$`\\]/.test(check)) throw new Error("STOP: check path cannot be quoted");
  return `"${check}"`;
}

const sha256 = (text) => createHash("sha256").update(text).digest("hex");

// ------------------------------------------------------------- the artefacts

/** The check script init generates when the repo owns none. */
export function checkScript(cmds) {
  const quoted = cmds.map((c) => `run '${c.replaceAll("'", "'\\''")}'`).join("\n");
  return `#!/usr/bin/env bash
# Generated by nightwatch init.mjs from the repo's CI steps. Runs each command
# in whatever directory it is invoked from, one line per step on success, the
# failing step's whole output on failure, and CHECK OK only when all passed.
set -uo pipefail
fail=0
run() {
  local out
  if out=$(bash -c "$1" 2>&1); then
    echo "✓ $1"
  else
    echo "✗ $1"
    printf '%s\\n' "$out"
    fail=1
  fi
}
${quoted}
[ "$fail" = 0 ] || exit 1
echo CHECK OK
`;
}

/**
 * The spec the dry run walks: it proves the engine can reconcile a branch and
 * run acceptance commands in this clone, and changes nothing while doing it.
 */
export function plumbingSpec(name, check) {
  return `# Plumbing check

Repo: ${name}

## Outcome

Prove the engine can reconcile a branch in this clone and run the repo's acceptance commands there. Nothing about the repo changes.

## Acceptance

- \`git rev-parse --abbrev-ref HEAD\` prints a branch name starting with \`nw/\`.
- \`git status --porcelain\` prints nothing.
- \`${checkCmd(check)}\` prints \`CHECK OK\` as its last line.

## Non-goals

- No edit to any file, and no commit: this outcome only observes.

## Context

- nightwatch init.mjs wrote this spec as the setup proof. Delete it once a real spec has run.
`;
}

/** `KEY=value` lines, no quoting and no expansion — run.sh reads them raw. */
function configText(cfg) {
  return `${Object.entries(cfg)
    .filter(([, v]) => v !== undefined && v !== "")
    .map(([k, v]) => `${k}=${v}`)
    .join("\n")}\n`;
}

/** The `run:` lines in .github/workflows/*.yml that look like local checks. */
export function checkSuggestions(repo) {
  const dir = join(repo, ".github", "workflows");
  if (!existsSync(dir)) return [];
  const out = [];
  for (const f of readdirSync(dir).sort()) {
    if (!/\.ya?ml$/.test(f)) continue;
    for (const line of readFileSync(join(dir, f), "utf8").split("\n")) {
      const m = line.match(/^\s*-?\s*run:\s*(\S.*?)\s*$/);
      if (!m || m[1] === "|" || m[1] === ">") continue;
      if (!CHECK_WORDS.test(m[1])) continue;
      if (!out.includes(m[1])) out.push(m[1]);
    }
  }
  return out;
}

// ------------------------------------------------------------------ the run

function normalize(opts = {}) {
  const home = opts.home || process.env.HOME || homedir();
  return {
    home,
    repo: opts.repo ? resolve(opts.repo) : process.cwd(),
    name: opts.name || "",
    cloneRoot: opts.cloneRoot ? resolve(opts.cloneRoot) : join(home, "Work", "Git", "nightwatch"),
    checkCmds: opts.checkCmds || [],
    stateVar: opts.stateVar || "LANDING_STATE",
    setSwitch: !!opts.setSwitch,
    noDryRun: !!opts.noDryRun,
    report: !!opts.report,
  };
}

/** What init would do, with no side effect of any kind. */
export function plan(opts = {}) {
  return run({ ...opts, report: true }).steps;
}

export function run(opts = {}) {
  const o = normalize(opts);
  const steps = [];
  const add = (step, status, detail = "") => {
    steps.push({ step, status, detail });
    return status;
  };
  const stop = (result) => ({ steps, ok: result, suggestions: [] });

  // ---- 1. preflight: nothing is written until this passes ----
  const missing = REQUIRED_BINS.filter((b) => !onPath(b));
  if (missing.length) {
    add("preflight", "failed", `not on PATH: ${missing.join(", ")}`);
    return stop(false);
  }
  if (process.env.ANTHROPIC_API_KEY) {
    add("preflight", "failed", "ANTHROPIC_API_KEY is set; the launcher refuses to run with it, because a night bills to the subscription only");
    return stop(false);
  }
  const auth = exec("gh", ["auth", "status"]);
  if (auth.code !== 0) {
    add("preflight", "failed", `gh auth status exited ${auth.code}: ${auth.stderr || auth.stdout}`);
    return stop(false);
  }
  add("preflight", "done", `${REQUIRED_BINS.join(", ")} on PATH, gh authenticated`);

  // ---- 2. the repo ----
  const top = exec("git", ["rev-parse", "--show-toplevel"], { cwd: o.repo });
  if (top.code !== 0) {
    add("repo", "failed", `${o.repo} is not a git checkout`);
    return stop(false);
  }
  const repo = top.stdout;
  const originRes = exec("git", ["remote", "get-url", "origin"], { cwd: repo });
  if (originRes.code !== 0) {
    add("repo", "failed", `${repo} has no origin remote`);
    return stop(false);
  }
  const origin = originRes.stdout;
  const head = exec("git", ["symbolic-ref", "--quiet", "refs/remotes/origin/HEAD"], { cwd: repo });
  const base = head.code === 0 && head.stdout ? head.stdout.replace(/^refs\/remotes\/origin\//, "") : "main";
  const name = o.name || basename(repo);
  const state = join(o.home, ".local", "state", "nightwatch", name);
  const clone = join(o.cloneRoot, name);

  const configPath = join(state, "config");
  if (existsSync(configPath)) {
    const prior = readFileSync(configPath, "utf8").match(/^ORIGIN=(.*)$/m);
    if (prior && prior[1] && prior[1] !== origin) {
      add("repo", "failed", `name ${name} is taken by ${prior[1]}; pass --name`);
      return stop(false);
    }
  }
  if (existsSync(join(clone, ".git"))) {
    const co = exec("git", ["remote", "get-url", "origin"], { cwd: clone });
    if (co.code === 0 && co.stdout !== origin) {
      add("repo", "failed", `name ${name} is taken by ${co.stdout}; pass --name`);
      return stop(false);
    }
  }
  add("repo", "done", `${name}: ${repo} → ${clone}, base ${base}`);

  // ---- 3. the clone ----
  if (existsSync(join(clone, ".git"))) {
    if (!o.report) {
      const fetched = exec("git", ["fetch", "-q", "origin"], { cwd: clone });
      if (fetched.code !== 0) {
        add("clone", "failed", `git fetch in ${clone}: ${fetched.stderr}`);
        return stop(false);
      }
      const dirty = exec("git", ["status", "--porcelain"], { cwd: clone });
      if (dirty.stdout) {
        add("clone", "failed", `clone is dirty: ${clone}`);
        return stop(false);
      }
    }
    add("clone", "skipped", `already cloned at ${clone}`);
  } else if (o.report) {
    add("clone", "would", `clone ${origin} into ${clone}`);
  } else {
    mkdirSync(o.cloneRoot, { recursive: true });
    const cloned = exec("git", ["clone", "-q", origin, clone]);
    if (cloned.code !== 0) {
      add("clone", "failed", `git clone: ${cloned.stderr || cloned.stdout}`);
      return stop(false);
    }
    add("clone", "done", `cloned ${origin} into ${clone}`);
  }

  // ---- 4. trust: the headless child never sees a trust dialog ----
  const claudeJson = join(o.home, ".claude.json");
  let cj = {};
  if (existsSync(claudeJson)) {
    try {
      cj = JSON.parse(readFileSync(claudeJson, "utf8"));
    } catch {
      add("trust", "failed", `${claudeJson} is not JSON; left exactly as it is`);
      return stop(false);
    }
    if (cj === null || typeof cj !== "object" || Array.isArray(cj)) {
      add("trust", "failed", `${claudeJson} is not a JSON object; left exactly as it is`);
      return stop(false);
    }
  }
  if (cj.projects?.[clone]?.hasTrustDialogAccepted === true) {
    add("trust", "skipped", `already trusted in ${claudeJson}`);
  } else if (o.report) {
    add("trust", "would", `trust ${clone} in ${claudeJson}`);
  } else {
    const bak = `${claudeJson}.nightwatch-bak`;
    if (existsSync(claudeJson) && !existsSync(bak)) copyFileSync(claudeJson, bak);
    cj.projects = cj.projects || {};
    cj.projects[clone] = { ...(cj.projects[clone] || {}), hasTrustDialogAccepted: true };
    const tmp = `${claudeJson}.nightwatch-tmp`;
    writeFileSync(tmp, `${JSON.stringify(cj, null, 2)}\n`);
    renameSync(tmp, claudeJson);
    add("trust", "done", `${clone} trusted in ${claudeJson}`);
  }

  // ---- 5. the check command ----
  let check = "";
  let checkSha = "";
  const suggestions = checkSuggestions(repo);
  if (existsSync(join(repo, "scripts", "check"))) {
    check = "scripts/check";
    add("check", "skipped", "repo has scripts/check");
  } else if (!o.checkCmds.length && existsSync(join(state, "check"))) {
    // A previous init generated one; a re-run (or --report) keeps it unless --check-cmd rewrites it.
    check = join(state, "check");
    checkSha = sha256(readFileSync(check, "utf8"));
    add("check", "skipped", `generated check at ${check} kept; pass --check-cmd to rewrite it`);
  } else if (!o.checkCmds.length) {
    add("check", "needs you", "pass --check-cmd once per CI step; --report lists the candidates");
    return { steps, ok: false, suggestions };
  } else if (o.report) {
    check = join(state, "check");
    add("check", "would", `write ${check} from ${o.checkCmds.length} command(s) and prove it in the clone`);
  } else {
    const script = join(state, "check");
    const text = checkScript(o.checkCmds);
    mkdirSync(state, { recursive: true });
    writeFileSync(script, text);
    chmodSync(script, 0o755);
    const log = join(state, "check-first-run.log");
    const first = exec("bash", [script], { cwd: clone });
    const body = [first.stdout, first.stderr].filter(Boolean).join("\n");
    writeFileSync(log, `${body}\n`);
    const last = body.split("\n").filter(Boolean).pop();
    if (first.code !== 0 || last !== "CHECK OK") {
      add("check", "failed", `the check does not pass in ${clone} today; see ${log}`);
      return { steps, ok: false, suggestions };
    }
    check = script;
    checkSha = sha256(text);
    add("check", "done", `${script} passes in the clone`);
  }
  // A path the rendering rule cannot quote would break every consumer downstream.
  try {
    checkCmd(check);
  } catch (e) {
    add("check", "failed", e.message);
    return { steps, ok: false, suggestions };
  }

  // ---- 6. the state directory ----
  const specs = join(state, "specs");
  const drySpecs = join(state, "dry-specs");
  if (o.report) {
    add("state", "would", `write ${configPath} and create ${specs} and ${drySpecs}`);
  } else {
    mkdirSync(specs, { recursive: true });
    mkdirSync(drySpecs, { recursive: true });
    writeFileSync(
      configPath,
      configText({ NAME: name, REPO: repo, ORIGIN: origin, CLONE: clone, SPECS: specs, BASE: base, STATE_VAR: o.stateVar, CHECK: check, CHECK_SHA: checkSha }),
    );
    add("state", "done", configPath);
  }

  // ---- 7. the kill switch ----
  const readSwitch = () => {
    const v = exec("gh", ["variable", "get", o.stateVar], { cwd: repo });
    return v.code === 0 ? v.stdout : "";
  };
  let switchOn = readSwitch() === "run";
  const setCmd = `gh variable set ${o.stateVar} --body run`;
  if (switchOn) {
    add("switch", "skipped", `${o.stateVar}=run`);
  } else if (!o.setSwitch) {
    add("switch", "needs you", `run \`${setCmd}\` in ${repo}`);
  } else if (o.report) {
    add("switch", "would", `run \`${setCmd}\` in ${repo}`);
  } else {
    const set = exec("gh", ["variable", "set", o.stateVar, "--body", "run"], { cwd: repo });
    if (set.code !== 0) {
      add("switch", "failed", `${setCmd}: ${set.stderr || set.stdout}`);
      return { steps, ok: false, suggestions };
    }
    switchOn = readSwitch() === "run";
    if (!switchOn) {
      add("switch", "failed", `${o.stateVar} still does not read run after setting it`);
      return { steps, ok: false, suggestions };
    }
    add("switch", "done", `${o.stateVar}=run`);
  }

  // ---- 8. the dry run: the only proof the plumbing works ----
  let dryOk = false;
  if (o.noDryRun) {
    add("dry-run", "skipped", "--no-dry-run");
    dryOk = true;
  } else if (o.report) {
    add("dry-run", "would", `run ${RUN_SH} ${name} ${drySpecs} --dry-run`);
  } else if (!switchOn) {
    add("dry-run", "needs you", "the switch is off, so the dry run did not start");
  } else {
    writeFileSync(join(drySpecs, "00-plumbing.md"), plumbingSpec(name, check));
    const journal = join(state, "journal.md");
    const before = existsSync(journal) ? statSync(journal).size : 0;
    const launched = exec("bash", [RUN_SH, name, drySpecs, "--dry-run"], { cwd: clone, env: process.env });
    const fresh = existsSync(journal) ? readFileSync(journal, "utf8").slice(before) : "";
    if (launched.code === 0 && /dry run complete/.test(fresh)) {
      add("dry-run", "done", "the engine reconciled a branch and ran the acceptance commands");
      dryOk = true;
    } else {
      const line = fresh.split("\n").filter((l) => /dry run/.test(l)).pop();
      add("dry-run", "failed", line || `the launcher exited ${launched.code}; see ${journal}`);
    }
  }

  const failed = steps.some((s) => s.status === "failed");
  return { steps, ok: !failed && (o.report || dryOk), suggestions };
}

// ------------------------------------------------------------------- the CLI

function parseArgs(argv) {
  const o = { checkCmds: [] };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    const next = () => {
      const v = argv[++i];
      if (v === undefined) {
        console.error(`${a} needs a value`);
        process.exit(64);
      }
      return v;
    };
    if (a === "--repo") o.repo = next();
    else if (a === "--name") o.name = next();
    else if (a === "--clone-root") o.cloneRoot = next();
    else if (a === "--check-cmd") o.checkCmds.push(next());
    else if (a === "--set-switch") o.setSwitch = true;
    else if (a === "--no-dry-run") o.noDryRun = true;
    else if (a === "--report") o.report = true;
    else if (a === "--json") o.json = true;
    else {
      console.error(`unknown argument ${a}`);
      process.exit(64);
    }
  }
  return o;
}

function renderStatus(s) {
  if (s.status === "skipped") return `skipped (${s.detail})`;
  if (s.status === "done") return "done";
  return `${s.status}: ${s.detail}`;
}

function main() {
  const o = parseArgs(process.argv.slice(2));
  const result = run(o);
  if (o.json) {
    console.log(JSON.stringify(result, null, 2));
    process.exit(result.ok ? 0 : 1);
  }
  const width = Math.max(...result.steps.map((s) => s.step.length), 8);
  for (const s of result.steps) {
    const detail = s.status === "done" && s.detail ? `  ${s.detail}` : "";
    console.log(`${s.step.padEnd(width)}  ${renderStatus(s)}${detail}`);
  }
  // Candidates are an answer to "what should --check-cmd say", so they belong
  // to --report and to the step that asks for them, not to every run.
  const wantsCheck = result.steps.some((s) => s.step === "check" && s.status === "needs you");
  if (result.suggestions.length && (o.report || wantsCheck)) {
    console.log("\ncheck-command candidates from .github/workflows:");
    for (const c of result.suggestions) console.log(`  --check-cmd "${c}"`);
  }
  const blocker = result.steps.find((s) => s.status === "failed" || s.status === "needs you");
  console.log(blocker ? `\n${blocker.step}: ${renderStatus(blocker)}` : "\nnext: /nightwatch:spec");
  process.exit(result.ok ? 0 : 1);
}

if (import.meta.url === `file://${process.argv[1]}`) main();
